version: "3"

services:
    node:
        image: node:current
        deploy:
            restart_policy:
                condition: on-failure
        working_dir: /app
        env_file: .env
        ports:
            - 80:80
        command: bash -c "npm run dev"
        # command: bash -c "npm run serve"
        volumes:
            - "./:/app"
